male_first_names = ['Ethan', 'Liam', 'Noah', 'Jacob', 'William', 'James', 'Benjamin', 'Michael', 'Alexander', 'Daniel',
                    'Matthew', 'David', 'Joseph', 'Andrew', 'Christopher', 'Samuel', 'Ryan', 'Nicholas', 'Jonathan', 'Tyler',
                    'Brandon', 'Kevin', 'Robert', 'Eric', 'Anthony', 'Kofi', 'Kwame', 'Kwasi', 'Kwabena', 'Yaw', 'Amoah',
                    'Brian', 'Charles', 'Jason', 'Adam', 'Thomas', 'Timothy', 'Hakeem', 'Jide', 'Kayin', 'Kehinde', 'Kamau', 'Kwadwo',
                    'Satoshi', 'Takumi', 'Hiroto', 'Ryota', 'Yuki', 'Kazuki', 'Haruki', 'Tatsuya', 'Masaki', 'Sho', 'Kenta',
                    'Makoto', 'Yuta', 'Hiroki', 'Shota', 'Koki', 'Toshiro', 'Jin', 'Ren', 'Shun', 'Yusei', 'Akihiro', 'Daiki',
                    'Ryosuke', 'Ryo', 'Shogo', 'Kensuke', 'Yosuke', 'Takeru', 'Sora',
                    'Caleb', 'Steven', 'Aaron', 'Nathan', 'Jeremy', 'Jeffrey', 'Justin', 'Kyle', 'Mark', 'Peter', 'Scott',
                    'Seth', 'Shane', 'Stephen', 'Simon', 'Spencer', 'Sean', 'Travis', 'Zachary']


female_first_names = ['Olivia', 'Emma', 'Ava', 'Sophia', 'Isabella', 'Mia', 'Charlotte', 'Amelia',
                      'Evelyn', 'Abigail', 'Harper', 'Emily', 'Elizabeth', 'Avery', 'Sofia', 'Ella', 'Madison', 'Scarlett', 'Victoria', 'Chloe', 'Grace',
                      'Lily', 'Hannah', 'Aria', 'Natalie', 'Eleanor', 'Addison', 'Audrey', 'Aurora', 'Brooklyn', 'Bella',
                      'Ellie', 'Aaliyah', 'Claire', 'Samantha', 'Aubrey', 'Leah', 'Lucy', 'Stella', 'Violet', 'Genesis',
                      'Katherine', 'Isabelle', 'Zoe', 'Penelope', 'Lillian', 'Allison', 'Maya', 'Hazel', 'Camila', 'Arianna',
                      'Eva', 'Layla', 'Gabriella', 'Serenity', 'Alexa', 'Savannah', 'Ariana', 'Caroline', 'Naomi', 'Sadie',
                      'Makayla', 'Autumn', 'Hailey', 'Piper', 'Lydia', 'Annabelle', 'Elliana', 'Kinsley', 'Maddison', 'Mila',
                      'Makenzie', 'Delilah', 'Amanda', 'Aria', 'Adeline', 'Eliana', 'Josephine', 'Mya', 'Kylie', 'Aubree',
                      'Kaitlyn', 'Gianna', 'Aurora', 'Melanie', 'Adalyn', 'Aubrie', 'Jocelyn', 'Fiona', 'Alaina', 'Alina',
                      'Lila', 'Raelynn', 'Vivian', 'Juliana', 'Kendall', 'Presley', 'Brielle']


last_names = ["Smith", "Johnson", "Williams", "Jones", "Brown", "Davis", "Miller",
              "Wilson", "Moore", "Taylor", "Anderson", "Thomas", "Jackson", "White",
              "Harris", "Martin", "Thompson", "Garcia", "Martinez", "Robinson",
              "Clark", "Rodriguez", "Lewis", "Lee", "Walker", "Hall", "Allen",
              "Young", "King", "Wright", "Scott", "Green", "Baker", "Adams",
              "Nelson", "Carter", "Mitchell", "Perez", "Roberts", "Turner",
              "Phillips", "Campbell", "Parker", "Evans", "Edwards", "Collins",
              "Stewart", "Sanchez", "Morris", "Rogers", "Reed", "Cook", "Morgan",
              "Bell", "Murphy", "Bailey", "Rivera", "Cooper", "Richardson", "Cox",
              "Howard", "Ward", "Torres", "Peterson", "Gray", "Ramirez", "James",
              "Watson", "Brooks", "Kelly", "Sanders", "Price", "Bennett", "Wood",
              "Barnes", "Ross", "Henderson", "Coleman", "Jenkins", "Perry",
              "Powell", "Sullivan", "Long", "Patterson", "Hughes", "Flores",
              "Washington", "Butler", "Simmons", "Foster", "Gonzalez", "Bryant",
              "Alexander", "Russell", "Griffin", "Diaz", "Hayes", "Myers", "Ford",
              "Hamilton", "Graham", "Sullivan", "Wallace", "Woods", "Cole",
              "West", "Jordan", "Owens", "Reynolds", "Fisher", "Ellis", "Harrison",
              "Gibson", "Mcdonald", "Cruz", "Marshall", "Ortiz", "Gomez", "Murray",
              "Freeman", "Wells", "Webb", "Simpson", "Stevens", "Tucker", "Porter",
              "Hunter", "Hicks", "Crawford", "Henry", "Boyd", "Mason", "Morales",
              "Kennedy", "Warren", "Dixon", "Ramos", "Reyes", "Burns", "Gordon",
              "Shaw", "Holmes", "Rice", "Robertson", "Hunt", "Black", "Daniels",
              "Palmer", "Mills", "Nichols", "Grant", "Knight", "Ferguson",
              "Rose", "Stone", "Hawkins", "Dunn", "Perkins", "Hudson", "Spencer",
              "Gardner", "Stephens", "Payne", "Pierce", "Berry", "Matthews",
              "Arnold", "Wagner", "Willis", "Ray", "Watkins", "Olson", "Carroll",
              "Duncan", "Snyder", "Hart", "Cunningham", "Bradley"]


commmon_street_names = ["High Street", "Station Road", "Church Street", "Main Street", "Park Road",
                        "The Green", "New Road", "Victoria Road", "Queens Road", "London Road", "Market Street",
                        "Kings Road", "School Lane", "Mill Lane", "Bridge Street", "Manor Road", "North Street",
                        "George Street", "West Street", "East Street", "Crescent Road", "Castle Street", "Hillside Avenue",
                        "Grove Road",  "Wellington Street",  "Chester Road", "Forest Avenue", "Woodside Lane",  "Springfield Road",
                        "Beach Road", "Albert Road", "Laurel Avenue", "Rose Lane", "Mount Pleasant", "Church Lane",
                        "Oxford Street", "Charles Street", "Holly Road", "Stratford Road",  "Highfield Road", "Brookside Close",
                        "Victoria Street", "Bridge Road", "Grange Road", "Primrose Avenue", "Acacia Avenue",
                        "Green Lane", "Lea Road", "The Avenue", "Elm Tree Road"]
